apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bonfire-image-owq7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bonfire-image-owq7
    app.kubernetes.io/part-of: bonfire-image-1
  name: bonfire-image-owq7ehln
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bonfire-image-owq7
    weight: 100
status: {}
